// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ad_bid.proto

#include "ad_bid.pb.h"
#include "ad_bid.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ad {

static const char* AdBidderService_method_names[] = {
  "/ad.AdBidderService/bidAd",
};

std::unique_ptr< AdBidderService::Stub> AdBidderService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AdBidderService::Stub> stub(new AdBidderService::Stub(channel, options));
  return stub;
}

AdBidderService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_bidAd_(AdBidderService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AdBidderService::Stub::bidAd(::grpc::ClientContext* context, const ::ad::BidRequest& request, ::ad::BidResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ad::BidRequest, ::ad::BidResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_bidAd_, context, request, response);
}

void AdBidderService::Stub::async::bidAd(::grpc::ClientContext* context, const ::ad::BidRequest* request, ::ad::BidResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ad::BidRequest, ::ad::BidResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_bidAd_, context, request, response, std::move(f));
}

void AdBidderService::Stub::async::bidAd(::grpc::ClientContext* context, const ::ad::BidRequest* request, ::ad::BidResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_bidAd_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ad::BidResponse>* AdBidderService::Stub::PrepareAsyncbidAdRaw(::grpc::ClientContext* context, const ::ad::BidRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ad::BidResponse, ::ad::BidRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_bidAd_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ad::BidResponse>* AdBidderService::Stub::AsyncbidAdRaw(::grpc::ClientContext* context, const ::ad::BidRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncbidAdRaw(context, request, cq);
  result->StartCall();
  return result;
}

AdBidderService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdBidderService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdBidderService::Service, ::ad::BidRequest, ::ad::BidResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdBidderService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ad::BidRequest* req,
             ::ad::BidResponse* resp) {
               return service->bidAd(ctx, req, resp);
             }, this)));
}

AdBidderService::Service::~Service() {
}

::grpc::Status AdBidderService::Service::bidAd(::grpc::ServerContext* context, const ::ad::BidRequest* request, ::ad::BidResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ad

