// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/ad_bid.proto
#ifndef GRPC_proto_2fad_5fbid_2eproto__INCLUDED
#define GRPC_proto_2fad_5fbid_2eproto__INCLUDED

#include "ad_bid.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace ad {

class AdBidderService final {
 public:
  static constexpr char const* service_full_name() {
    return "ad.AdBidderService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status bidAd(::grpc::ClientContext* context, const ::ad::BidRequest& request, ::ad::BidResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ad::BidResponse>> AsyncbidAd(::grpc::ClientContext* context, const ::ad::BidRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ad::BidResponse>>(AsyncbidAdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ad::BidResponse>> PrepareAsyncbidAd(::grpc::ClientContext* context, const ::ad::BidRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ad::BidResponse>>(PrepareAsyncbidAdRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void bidAd(::grpc::ClientContext* context, const ::ad::BidRequest* request, ::ad::BidResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void bidAd(::grpc::ClientContext* context, const ::ad::BidRequest* request, ::ad::BidResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ad::BidResponse>* AsyncbidAdRaw(::grpc::ClientContext* context, const ::ad::BidRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ad::BidResponse>* PrepareAsyncbidAdRaw(::grpc::ClientContext* context, const ::ad::BidRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status bidAd(::grpc::ClientContext* context, const ::ad::BidRequest& request, ::ad::BidResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ad::BidResponse>> AsyncbidAd(::grpc::ClientContext* context, const ::ad::BidRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ad::BidResponse>>(AsyncbidAdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ad::BidResponse>> PrepareAsyncbidAd(::grpc::ClientContext* context, const ::ad::BidRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ad::BidResponse>>(PrepareAsyncbidAdRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void bidAd(::grpc::ClientContext* context, const ::ad::BidRequest* request, ::ad::BidResponse* response, std::function<void(::grpc::Status)>) override;
      void bidAd(::grpc::ClientContext* context, const ::ad::BidRequest* request, ::ad::BidResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ad::BidResponse>* AsyncbidAdRaw(::grpc::ClientContext* context, const ::ad::BidRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ad::BidResponse>* PrepareAsyncbidAdRaw(::grpc::ClientContext* context, const ::ad::BidRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_bidAd_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status bidAd(::grpc::ServerContext* context, const ::ad::BidRequest* request, ::ad::BidResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_bidAd : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_bidAd() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_bidAd() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status bidAd(::grpc::ServerContext* /*context*/, const ::ad::BidRequest* /*request*/, ::ad::BidResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestbidAd(::grpc::ServerContext* context, ::ad::BidRequest* request, ::grpc::ServerAsyncResponseWriter< ::ad::BidResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_bidAd<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_bidAd : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_bidAd() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ad::BidRequest, ::ad::BidResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ad::BidRequest* request, ::ad::BidResponse* response) { return this->bidAd(context, request, response); }));}
    void SetMessageAllocatorFor_bidAd(
        ::grpc::MessageAllocator< ::ad::BidRequest, ::ad::BidResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ad::BidRequest, ::ad::BidResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_bidAd() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status bidAd(::grpc::ServerContext* /*context*/, const ::ad::BidRequest* /*request*/, ::ad::BidResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* bidAd(
      ::grpc::CallbackServerContext* /*context*/, const ::ad::BidRequest* /*request*/, ::ad::BidResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_bidAd<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_bidAd : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_bidAd() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_bidAd() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status bidAd(::grpc::ServerContext* /*context*/, const ::ad::BidRequest* /*request*/, ::ad::BidResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_bidAd : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_bidAd() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_bidAd() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status bidAd(::grpc::ServerContext* /*context*/, const ::ad::BidRequest* /*request*/, ::ad::BidResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestbidAd(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_bidAd : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_bidAd() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->bidAd(context, request, response); }));
    }
    ~WithRawCallbackMethod_bidAd() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status bidAd(::grpc::ServerContext* /*context*/, const ::ad::BidRequest* /*request*/, ::ad::BidResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* bidAd(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_bidAd : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_bidAd() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ad::BidRequest, ::ad::BidResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ad::BidRequest, ::ad::BidResponse>* streamer) {
                       return this->StreamedbidAd(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_bidAd() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status bidAd(::grpc::ServerContext* /*context*/, const ::ad::BidRequest* /*request*/, ::ad::BidResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedbidAd(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ad::BidRequest,::ad::BidResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_bidAd<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_bidAd<Service > StreamedService;
};

}  // namespace ad


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_proto_2fad_5fbid_2eproto__INCLUDED
